<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PackageId>Almostengr.Common</PackageId>
    <Company>Robinson Handy and Technology Services LLC</Company>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(yyyy)) Robinson Handy and Technology Services</Copyright>
    <Product>Almostengr Common Library</Product>
    <Authors>Kenny Robinson</Authors>
    <Description>Common generic classes and methods used for building MVC and Web API applications.</Description>
    <AssemblyName>Almostengr.Common</AssemblyName>
    <RootNamespace>Almostengr.Common</RootNamespace>
    <Version>10.$([System.DateTime]::UtcNow.ToString(yyyy.MMdd.HHmm))</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/almostengr/almostengr.common.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/almostengr/almostengr.common</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.9" />
    <None Include="README.md" Pack="true" PackagePath="\" />
    <PackageReference Include="Square" Version="44.0.0" />
  </ItemGroup>
</Project>
